apiVersion: v2
version: 0.0.1
appVersion: v0.8.0-incubating-SNAPSHOT
name: spark-cluster
metadata:  
  namespace: spark
  annotations:
    argocd.argoproj.io/sync-options: CreateNamespace=true

dependencies:
  - name: spark-cluster
    version: 2.0.1
    repository: https://jahstreet.github.io/helm-charts
    alias: spark-cluster

spec:
  project: spark-cluster

  source:
    repoURL: 'https://github.com/mw-a/spark-on-k8s.git'
    targetRevision: HEAD
    path: .

    helm:
      valueFiles:
      - values.yaml

      version: v2

  destination:
    server: https://kubernetes.default.svc
    namespace: spark

  syncPolicy:
    automated:
      prune: false
      selfHeal: false
